import type { Context } from '@deepseek-ai/cordis';
import Schema from '@deepseek-ai/schemastery';
import { MailboxEnvelopeCodec } from './mailbox-envelope.js';
import type { Transport } from './transport.js';
export declare const name = "a2a-messenger";
export declare const inject: string[];
export interface Config {
    agentName: string;
    deviceName: string;
    transport: 'none' | 'github' | 'filesystem' | 'teammcp';
    dataDir: string;
    trustedPeers: string[];
    githubRepo: string;
    githubToken: string;
    githubChannels: string[];
    githubPollSeconds: number;
    filesystemDir: string;
    filesystemPollSeconds: number;
    mailboxEncryption: 'readable' | 'sealed';
    mailboxRoute: string;
    mailboxTtlHours: number;
    directIcePolicy: 'strict' | 'stun' | 'relay';
    stunServers: string[];
    turnServers: string[];
    turnUsername: string;
    turnCredential: string;
    serverUrl: string;
    token: string;
}
export declare const Config: Schema<Config>;
export declare function parseTrustedPeers(entries: readonly string[]): ReadonlyMap<string, string>;
export declare function buildTransport(config: Config, dataDir: string, security?: {
    codec: MailboxEnvelopeCodec;
    mode: 'readable' | 'sealed';
}): Transport;
export declare function apply(ctx: Context, config: Config): void;
export { QuarantineInbox } from './inbox.js';
export { MessengerService } from './service.js';
export { SseSubscription } from './sse.js';
export { TeamMcpClient, TeamMcpError, normalizeIncoming } from './teammcp-client.js';
export { GitHubTransport, GitHubTransportError } from './transports/github.js';
export { TeamMcpTransport } from './transports/teammcp.js';
export { DirectSessionManager } from './direct/session.js';
export { createDirectIdentity, fingerprintPublicKey, openDirectIdentity, } from './direct/identity.js';
export { decodeCode, encodeCode } from './direct/codec.js';
export { NoneTransport } from './transports/none.js';
export { CompositeTransport } from './transports/composite.js';
export { FilesystemTransport } from './transports/filesystem.js';
export { SecureTransport } from './transports/secure.js';
export { ContactStore, decodeContactCard, encodeContactCard } from './contacts.js';
export { MailboxEnvelopeCodec } from './mailbox-envelope.js';
export { RendezvousCoordinator } from './rendezvous.js';
export { buildCommandDefs, buildToolDefs, formatInjection, parseTarget, } from './surface.js';
export type { Transport, TransportState, TransportSendInput } from './transport.js';
export type { IncomingMessage, QuarantinedMessage, QuarantineStatus } from './types.js';
export type { Contact, ContactTrust } from './contacts.js';
export type { MailboxSecurity } from './transports/secure.js';
export type { DirectDiagnostics, DirectReceipt, DirectReceiptStatus, IcePolicy } from './direct/session.js';
